apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hass
  namespace: flux-system
spec:
  interval: 1m
  path: clusters/scalos/kubernetes/apps/hass/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

