---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-backups-nfs-pv
  namespace: media
spec:
  storageClassName: media-backups-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.25
    path: "/mnt/downloads/soft/cluster-backup"
  mountOptions:
    - nfsvers=4
    - tcp
    - intr
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-backups-pvc
  namespace: media
spec:
  storageClassName: media-backups-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
