apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/scalos/kubernetes/system/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

